version: "3.9"

services:
  web:
    volumes:
      - ${PWD}/events.txt:/app/events.txt
    ports:
      - 8001:8001
    environment:
      VIRTUAL_PORT: 8001
      VIRTUAL_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu
      #LETSENCRYPT_HOST: talks.cosi.clarkson.edu,talks.cslabs.clarkson.edu
    build:
      context: .
      args: 
        VIRTUAL_PORT: 8001

networks:
  default:
    external:
      name: nginx-proxy
